### ISSUE TITLE
ESPHome i2s_audio compatibility

### ISSUE THREAD

**Issue by NonaSuomy** [CelliesProjects/wm8978-esp32#10]
Would it be plausible to make this compatible with https://github.com/esphome/esphome/tree/dev/esphome/components/i2s_audio

https://esphome.io/components/media_player/i2s_audio.html

https://rc.home-assistant.io/projects/thirteen-usd-voice-remote/

Thank you.

**Comment by NonaSuomy** [comment]
YAML could look something like this
```yaml
substitutions:
  name: "t-audio-001"
  friendly_name: "T-Audio-001"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key005

ota:
  password: !secret ota_pass005

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: !secret use_address_wifi005

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} Fallback Hotspot"
    password: !secret fallbackhotspot005

captive_portal:
web_server:
switch:
  - platform: restart
    name: "${friendly_name} Restart"
i2c:
  sda: GPIO19
  scl: GPIO18
i2s_audio:
  i2s_lrclk_pin: GPIO25
  i2s_bclk_pin: GPIO33
  # Missing this pin setup?
  #i2s_mclk_pin: 0

microphone:
  - platform: i2s_audio
    id: echo_microphone
    i2s_din_pin: GPIO27

voice_assistant:
  # Maybe need a setup component for the wm8978 mic input.
  #microphone: wm8978_microphone

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO34
      inverted: true
    name: ${friendly_name} Button
    id: echo_button
    on_press:
      - voice_assistant.start:
    on_release:
      - voice_assistant.stop:
    on_click:
      - media_player.toggle: media_out

media_player:
  - platform: i2s_audio
    id: media_out
    name: ${friendly_name}
    dac_type: external
    i2s_dout_pin: GPIO26
    mode: mono

# Need a wm8978 component
#wm8978:

light:
  - platform: fastled_clockless
    id: led
    name: "${friendly_name} LEDs"
    pin: GPIO22
    chipset: NEOPIXEL
    num_leds: 19
    #rgb_order: grb
    #effects:
    #  - addressable_rainbow:
    #  - addressable_rainbow:
    #      name: Rainbow Effect With Custom Values
    #      speed: 10
    #      width: 50
```

It basically works (Button and LED haha) besides the wm8978 initialization code missing.
